name: First Workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: hellow GitHub Action
              run: echo "hellow this is firs working in githubh action"
            - name: Bye Github action
              run: echo  "bye github"
            # - name: fail job intentionally
            #   run: "exit 1"
