name: Validate files
on: workflow_dispatch
jobs:
    validate-file:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v4
            
            - name: Validate index.js
              run: test -f index.js        

            - name: Validate index.html
              run: test -f index.html